import Head from "next/head";
import Card from "../components/Card";
import { Technology } from "../constant/technology";
import { SuffleArray } from "../utils/SuffleArray";
import { useState } from "react";

export default function Home() {

  const [randomTech, setrandomTech] = useState(
    SuffleArray(Technology)
  );

  const handleSuffle: () => void = () => {
    const randomData = SuffleArray(Technology);
    setrandomTech([...randomData]);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card randomTech={randomTech} handleSuffle={handleSuffle} />
    </div>
  );
}
